// Generated by CoffeeScript 1.3.3
(function() {

  ({
    rt: (typeof exports !== "undefined" && exports !== null) && exports || this.rt || (this.rt = {})
  });

  describe('Camera', function() {
    var camera;
    camera = null;
    beforeEach(function() {
      var direction, position;
      position = new rt.Vector3D(0.0, 0.0, 0.0);
      direction = new rt.Vector3D(1.0, 0.0, 0.0);
      camera = new rt.Camera(position, direction);
    });
    it('is an object', function() {
      return expect(camera instanceof rt.Object).toBe(true);
    });
    it('can be initialized', function() {
      expect(camera.position.x).toBe(0.0);
      expect(camera.position.y).toBe(0.0);
      expect(camera.position.z).toBe(0.0);
      expect(camera.direction.x).toBe(1.0);
      expect(camera.direction.y).toBe(0.0);
      expect(camera.direction.z).toBe(0.0);
      expect(camera.right.x).toBe(0.0);
      expect(camera.right.y).toBe(0.0);
      expect(camera.right.z).toBe(-1.5);
      expect(camera.up.x).toBe(0.0);
      expect(camera.up.y).toBe(1.5);
      return expect(camera.up.z).toBe(0.0);
    });
    return it('can be validated', function() {
      var valid_camera;
      valid_camera = camera.IsValid();
      return expect(valid_camera).toBe(true);
    });
  });

}).call(this);
