// Generated by CoffeeScript 1.3.3
(function() {

  ({
    rt: (typeof exports !== "undefined" && exports !== null) && exports || this.rt || (this.rt = {})
  });

  describe('GeometricObject', function() {
    var geometric_object;
    geometric_object = null;
    beforeEach(function() {
      geometric_object = new rt.GeometricObject();
    });
    it('is an object', function() {
      return expect(geometric_object instanceof rt.Object).toBe(true);
    });
    return it('is an interface', function() {
      expect(typeof geometric_object.IsValid).toBe("function");
      expect(geometric_object.IsValid()).toBe(false);
      expect(typeof geometric_object.Normal).toBe("function");
      expect(geometric_object.Normal()).toBeNull();
      expect(typeof geometric_object.Intersect).toBe("function");
      return expect(geometric_object.Intersect()).toBeNull();
    });
  });

}).call(this);
