// Generated by CoffeeScript 1.3.3
(function() {

  ({
    rt: (typeof exports !== "undefined" && exports !== null) && exports || this.rt || (this.rt = {})
  });

  describe('Light', function() {
    var light;
    light = null;
    beforeEach(function() {
      var color, position;
      position = new rt.Vector3D(2.0, 3.0, 4.0);
      color = new rt.RGBColor(0.1, 0.3, 0.8);
      light = new rt.Light(position, color);
    });
    it('is an object', function() {
      return expect(light instanceof rt.Object).toBe(true);
    });
    it('can be initialized', function() {
      expect(light.position.x).toBe(2.0);
      expect(light.position.y).toBe(3.0);
      expect(light.position.z).toBe(4.0);
      expect(light.color.red).toBe(0.1);
      expect(light.color.green).toBe(0.3);
      return expect(light.color.blue).toBe(0.8);
    });
    return it('can be validated', function() {
      var valid_light;
      valid_light = light.IsValid();
      return expect(valid_light).toBe(true);
    });
  });

}).call(this);
