// Generated by CoffeeScript 1.3.3
(function() {

  ({
    rt: (typeof exports !== "undefined" && exports !== null) && exports || this.rt || (this.rt = {})
  });

  describe('Object', function() {
    var object;
    object = null;
    beforeEach(function() {
      object = new rt.Object();
    });
    return it('is an interface', function() {
      expect(typeof object.IsValid).toBe("function");
      return expect(object.IsValid()).toBe(false);
    });
  });

}).call(this);
