// Generated by CoffeeScript 1.3.3
(function() {

  ({
    rt: (typeof exports !== "undefined" && exports !== null) && exports || this.rt || (this.rt = {})
  });

  describe('RayTracer', function() {
    var ray_tracer;
    ray_tracer = null;
    return beforeEach(function() {
      ray_tracer = new rt.RayTracer(5);
    });
  });

}).call(this);
