// Generated by CoffeeScript 1.3.3
(function() {

  ({
    rt: (typeof exports !== "undefined" && exports !== null) && exports || this.rt || (this.rt = {})
  });

  describe('Ray', function() {
    var ray;
    ray = null;
    beforeEach(function() {
      var direction, origin;
      origin = new rt.Vector3D(2.0, 3.0, 4.0);
      direction = new rt.Vector3D(1.0, 0.0, 0.0);
      ray = new rt.Ray(origin, direction);
    });
    it('is an object', function() {
      return expect(ray instanceof rt.Object).toBe(true);
    });
    it('can be initialized', function() {
      expect(ray.origin.x).toBe(2.0);
      expect(ray.origin.y).toBe(3.0);
      expect(ray.origin.z).toBe(4.0);
      expect(ray.direction.x).toBe(1.0);
      expect(ray.direction.y).toBe(0.0);
      return expect(ray.direction.z).toBe(0.0);
    });
    return it('can be validated', function() {
      var valid_ray;
      valid_ray = ray.IsValid();
      return expect(valid_ray).toBe(true);
    });
  });

}).call(this);
