// Generated by CoffeeScript 1.3.3
(function() {

  ({
    rt: (typeof exports !== "undefined" && exports !== null) && exports || this.rt || (this.rt = {})
  });

  describe('Surface', function() {
    var surface;
    surface = null;
    beforeEach(function() {
      surface = new rt.Surface();
    });
    it('is an object', function() {
      return expect(surface instanceof rt.Object).toBe(true);
    });
    return it('is an interface', function() {
      expect(typeof surface.roughness).toBe("number");
      expect(surface.roughness).toEqual(0);
      expect(typeof surface.IsValid).toBe("function");
      expect(surface.IsValid()).toBe(false);
      expect(typeof surface.Diffuse).toBe("function");
      expect(surface.Diffuse()).toBeNull();
      expect(typeof surface.Specular).toBe("function");
      expect(surface.Specular()).toBeNull();
      expect(typeof surface.Reflect).toBe("function");
      return expect(surface.Reflect()).toBeNull();
    });
  });

}).call(this);
