// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ({
    rt: (typeof exports !== "undefined" && exports !== null) && exports || this.rt || (this.rt = {})
  });

  rt.Camera = (function(_super) {

    __extends(Camera, _super);

    function Camera(position, direction) {
      var down;
      if ((position != null) && (direction != null)) {
        if (!position instanceof rt.Vector3D || !(typeof position.IsValid === "function" ? position.IsValid() : void 0) || !direction instanceof rt.Vector3D || !(typeof direction.IsValid === "function" ? direction.IsValid() : void 0)) {
          throw new TypeError;
        }
      } else {
        throw new TypeError;
      }
      down = new rt.Vector3D(0.0, -1.0, 0.0);
      this.position = new rt.Vector3D(position.x, position.y, position.z);
      this.direction = new rt.Vector3D();
      this.direction.SetV(this.position).Add(direction).Normalize();
      this.right = new rt.Vector3D();
      this.right.SetV(this.direction.Cross(down).Normalize()).Scale(1.5);
      this.up = new rt.Vector3D();
      this.up.SetV(this.direction.Cross(this.right).Normalize()).Scale(1.5);
    }

    Camera.prototype.IsValid = function() {
      return this.position.IsValid() && this.direction.IsValid();
    };

    return Camera;

  })(rt.Object);

}).call(this);
