// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ({
    rt: (typeof exports !== "undefined" && exports !== null) && exports || this.rt || (this.rt = {})
  });

  rt.GeometricObject = (function(_super) {

    __extends(GeometricObject, _super);

    function GeometricObject() {
      return GeometricObject.__super__.constructor.apply(this, arguments);
    }

    GeometricObject.prototype.IsValid = function() {
      return false;
    };

    GeometricObject.prototype.Normal = function(position) {
      return null;
    };

    GeometricObject.prototype.Intersect = function(ray) {
      return null;
    };

    return GeometricObject;

  })(rt.Object);

}).call(this);
