// Generated by CoffeeScript 1.3.3
(function() {

  ({
    rt: (typeof exports !== "undefined" && exports !== null) && exports || this.rt || (this.rt = {})
  });

  rt.MathLibrary = (function() {

    function MathLibrary() {}

    MathLibrary.IsValid = function(scalar) {
      return !isNaN(scalar);
    };

    return MathLibrary;

  })();

}).call(this);
