// Generated by CoffeeScript 1.3.3
(function() {

  ({
    rt: (typeof exports !== "undefined" && exports !== null) && exports || this.rt || (this.rt = {})
  });

  rt.MathLibrary = (function() {

    function MathLibrary() {}

    MathLibrary.IsValid = function(scalar) {
      return !isNaN(scalar);
    };

    MathLibrary.ClampScalar = function(scalar, lower_limit, upper_limit) {
      return Math.max(lower_limit, Math.min(scalar, upper_limit));
    };

    return MathLibrary;

  })();

}).call(this);
