// Generated by CoffeeScript 1.3.3
(function() {

  ({
    rt: (typeof exports !== "undefined" && exports !== null) && exports || this.rt || (this.rt = {})
  });

  rt.Object = (function() {

    function Object() {}

    Object.prototype.IsValid = function() {
      return false;
    };

    return Object;

  })();

}).call(this);
