// Generated by CoffeeScript 1.3.3
(function() {

  ({
    rt: (typeof exports !== "undefined" && exports !== null) && exports || this.rt || (this.rt = {})
  });

  rt.RGBColor = (function() {

    function RGBColor(red, green, blue) {
      var _ref, _ref1, _ref2;
      if ((red != null) && !rt.MathLibrary.IsValid(red) || (green != null) && !rt.MathLibrary.IsValid(green) || (blue != null) && !rt.MathLibrary.IsValid(blue)) {
        throw new TypeError;
      } else {
        this.red = (_ref = rt.MathLibrary.ClampScalar(red, 0.0, 1.0)) != null ? _ref : 0.0;
        this.green = (_ref1 = rt.MathLibrary.ClampScalar(green, 0.0, 1.0)) != null ? _ref1 : 0.0;
        this.blue = (_ref2 = rt.MathLibrary.ClampScalar(blue, 0.0, 1.0)) != null ? _ref2 : 0.0;
      }
    }

    RGBColor.prototype.IsValid = function() {
      return rt.MathLibrary.IsValid(this.red) && rt.MathLibrary.IsValid(this.green) && rt.MathLibrary.IsValid(this.blue);
    };

    RGBColor.prototype.Add = function(color) {
      if (color != null) {
        if (!(typeof color.IsValid === "function" ? color.IsValid() : void 0)) {
          throw new TypeError;
        }
      } else {
        throw new TypeError;
      }
      this.red = rt.MathLibrary.ClampScalar(this.red + color.red, 0.0, 1.0);
      this.green = rt.MathLibrary.ClampScalar(this.green + color.green, 0.0, 1.0);
      this.blue = rt.MathLibrary.ClampScalar(this.blue + color.blue, 0.0, 1.0);
      return this;
    };

    RGBColor.prototype.Scale = function(scalar) {
      if (!(scalar != null) || !rt.MathLibrary.IsValid(scalar)) {
        throw new TypeError;
      }
      this.red = rt.MathLibrary.ClampScalar(scalar * this.red, 0.0, 1.0);
      this.green = rt.MathLibrary.ClampScalar(scalar * this.green, 0.0, 1.0);
      this.blue = rt.MathLibrary.ClampScalar(scalar * this.blue, 0.0, 1.0);
      return this;
    };

    RGBColor.prototype.Multiply = function(color) {
      if (color != null) {
        if (!(typeof color.IsValid === "function" ? color.IsValid() : void 0)) {
          throw new TypeError;
        }
      } else {
        throw new TypeError;
      }
      this.red = rt.MathLibrary.ClampScalar(this.red * color.red, 0.0, 1.0);
      this.green = rt.MathLibrary.ClampScalar(this.green * color.green, 0.0, 1.0);
      this.blue = rt.MathLibrary.ClampScalar(this.blue * color.blue, 0.0, 1.0);
      return this;
    };

    RGBColor.prototype.getDrawingColor = function() {
      return {
        'red': Math.floor(rt.MathLibrary.ClampScalar(this.red, 0.0, 1.0) * 255),
        'green': Math.floor(rt.MathLibrary.ClampScalar(this.green, 0.0, 1.0) * 255),
        'blue': Math.floor(rt.MathLibrary.ClampScalar(this.blue, 0.0, 1.0) * 255)
      };
    };

    return RGBColor;

  })();

  rt.RGBStaticColors = (function() {

    function RGBStaticColors() {}

    RGBStaticColors.white = new rt.RGBColor(1.0, 1.0, 1.0);

    RGBStaticColors.grey = new rt.RGBColor(0.5, 0.5, 0.5);

    RGBStaticColors.black = new rt.RGBColor(0.0, 0.0, 0.0);

    RGBStaticColors.background = RGBStaticColors.black;

    RGBStaticColors["default"] = RGBStaticColors.black;

    return RGBStaticColors;

  })();

}).call(this);
