// Generated by CoffeeScript 1.3.3
(function() {

  ({
    rt: (typeof exports !== "undefined" && exports !== null) && exports || this.rt || (this.rt = {})
  });

  rt.StaticObject = (function() {

    function StaticObject() {}

    return StaticObject;

  })();

}).call(this);
