// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ({
    rt: (typeof exports !== "undefined" && exports !== null) && exports || this.rt || (this.rt = {})
  });

  rt.Surface = (function(_super) {

    __extends(Surface, _super);

    function Surface() {
      this.roughness = 0;
    }

    Surface.prototype.IsValid = function() {
      return false;
    };

    Surface.prototype.Diffuse = function() {
      return null;
    };

    Surface.prototype.Specular = function() {
      return null;
    };

    Surface.prototype.Reflect = function() {
      return null;
    };

    return Surface;

  })(rt.Object);

}).call(this);
